Resolved error so removed section
Created a bug for myself, what a skill! 🤦🏼‍♀️
I had included an additional field 'series: [""] ' in my front matter which caused the error on build 🙃
Remove the field!!

```
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:5:8: executing "_default/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: partials/templates/opengraph.html:45:17: executing "partials/templates/opengraph.html" at <index $siteSeries ($name | urlize)>: error calling index: index of untyped nil
```